### ISSUE TITLE
Doctests of `trixi_include` fail

### ISSUE THREAD

**Issue by JoshuaLampert** [trixi-framework/TrixiBase.jl#12]
The [doctest](https://github.com/trixi-framework/TrixiBase.jl/blob/152f79472e342e3069fc0adea7b3ba938c4d56d1/src/trixi_include.jl#L21-L29) of `trixi_include` [fail because `examples_dir()` is not defined](https://github.com/JoshuaLampert/DispersiveShallowWater.jl/actions/runs/7830915606/job/21366089396?pr=88) although [I set](https://github.com/JoshuaLampert/DispersiveShallowWater.jl/pull/88/files#diff-4aae2d1c783cade58bd2cb13748da956e568b7f2aed5fafd9e2a46fb97daf613)
```julia
DocMeta.setdocmeta!(TrixiBase, :DocTestSetup, :(using TrixiBase); recursive = true)
```
What can I do such that this works or if there is no (easy) way, what should we do?

**Comment by efaulhaber** [comment]
IMO it doesn't really make sense to have a Trixi example in the TrixiBase docs.

**Comment by JoshuaLampert** [comment]
What if we just make it a usual example, but remove the jldoctest?
