### ISSUE TITLE
Format error shouldn't prevent tests from running

### ISSUE THREAD

**Issue by sloede** [trixi-framework/TrixiBase.jl#4]
What's the rationale behind stopping all tests if the format is wrong? My dev workflow is often incremental, thus I do a little thing, push, then come back later once tests have run. If the only thing missing the formatting while all functional tests are green, I usually just apply the formatter and immediately request a review.

IMHO, we should either make the format check a separate run on a single OS, or move it to the end of the tests. I prefer the former. Thoughts @efaulhaber @ranocha ?

**Comment by ranocha** [comment]
I also prefer the first option. IIRC, @efaulhaber told me that he uses it like it is since that saves CI time in private repositories - fail fast if anything isn't correct.

**Comment by efaulhaber** [comment]
Yes, that's what we use for TrixiParticles to avoid wasting CI time when the run will fail anyway.
